flags:
  serversession-backend-acid-state:
    lib-Werror: true
  serversession-frontend-wai:
    lib-Werror: true
  serversession-backend-persistent:
    lib-Werror: true
  serversession:
    lib-Werror: true
  serversession-backend-redis:
    lib-Werror: true
  serversession-frontend-yesod:
    lib-Werror: true
packages:
  - serversession
  - serversession-backend-acid-state
  - serversession-backend-persistent
  - serversession-backend-redis
  - serversession-frontend-wai
  - serversession-frontend-yesod
  - examples/serversession-example-yesod-persistent
resolver: lts-19.5
