packages:
  - serversession
  - serversession-backend-acid-state
  - serversession-backend-persistent
  - serversession-backend-redis
  - serversession-frontend-wai
  - serversession-frontend-yesod
  - examples/serversession-example-yesod-persistent
resolver: lts-19.5
