on: [push]
jobs:
  serversession-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
      - uses: actions/cache@v3
        with:
          path: |
            .stack-work/
            ~/.stack/
          key: serversession-test-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('serversession/serversession.cabal') }}
          restore-keys: |
            serversession-test-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('serversession/serversession.cabal') }}
            serversession-test-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-
      - run: stack test serversession:test:tests
